# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HW9.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 800)
        self.groupInput = QtWidgets.QGroupBox(Dialog)
        self.groupInput.setGeometry(QtCore.QRect(20, 10, 861, 131))
        self.groupInput.setObjectName("groupInput")
        self.txtFileName = QtWidgets.QLineEdit(self.groupInput)
        self.txtFileName.setGeometry(QtCore.QRect(100, 40, 631, 31))
        self.txtFileName.setReadOnly(False)
        self.txtFileName.setObjectName("txtFileName")
        self.lblFilename = QtWidgets.QLabel(self.groupInput)
        self.lblFilename.setGeometry(QtCore.QRect(30, 40, 61, 31))
        self.lblFilename.setObjectName("lblFilename")
        self.btnSelect = QtWidgets.QPushButton(self.groupInput)
        self.btnSelect.setGeometry(QtCore.QRect(740, 40, 93, 31))
        self.btnSelect.setObjectName("btnSelect")
        self.layoutWidget = QtWidgets.QWidget(self.groupInput)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 80, 801, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbtnLin = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtnLin.setObjectName("rbtnLin")
        self.horizontalLayout.addWidget(self.rbtnLin)
        self.rbtnQuad = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtnQuad.setObjectName("rbtnQuad")
        self.horizontalLayout.addWidget(self.rbtnQuad)
        self.rbtnCubic = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtnCubic.setObjectName("rbtnCubic")
        self.horizontalLayout.addWidget(self.rbtnCubic)
        self.rbtnExp = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtnExp.setChecked(False)
        self.rbtnExp.setObjectName("rbtnExp")
        self.horizontalLayout.addWidget(self.rbtnExp)
        self.rbtnAll = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtnAll.setChecked(True)
        self.rbtnAll.setObjectName("rbtnAll")
        self.horizontalLayout.addWidget(self.rbtnAll)
        self.groupOutput = QtWidgets.QGroupBox(Dialog)
        self.groupOutput.setGeometry(QtCore.QRect(20, 200, 861, 521))
        self.groupOutput.setObjectName("groupOutput")
        self.lblEquation = QtWidgets.QLabel(self.groupOutput)
        self.lblEquation.setGeometry(QtCore.QRect(30, 40, 61, 31))
        self.lblEquation.setObjectName("lblEquation")
        self.txtEquation = QtWidgets.QLineEdit(self.groupOutput)
        self.txtEquation.setGeometry(QtCore.QRect(100, 40, 731, 31))
        self.txtEquation.setReadOnly(True)
        self.txtEquation.setObjectName("txtEquation")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupOutput)
        self.graphicsView.setGeometry(QtCore.QRect(30, 100, 801, 391))
        self.graphicsView.setObjectName("graphicsView")
        self.btnCalc = QtWidgets.QPushButton(Dialog)
        self.btnCalc.setGeometry(QtCore.QRect(340, 160, 221, 28))
        self.btnCalc.setObjectName("btnCalc")
        self.btnExit = QtWidgets.QPushButton(Dialog)
        self.btnExit.setGeometry(QtCore.QRect(340, 750, 221, 28))
        self.btnExit.setObjectName("btnExit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupInput.setTitle(_translate("Dialog", "Input"))
        self.lblFilename.setText(_translate("Dialog", "Filename:"))
        self.btnSelect.setText(_translate("Dialog", "Select File"))
        self.rbtnLin.setText(_translate("Dialog", "Linear Fit"))
        self.rbtnQuad.setText(_translate("Dialog", "Quadratic Fit"))
        self.rbtnCubic.setText(_translate("Dialog", "Cubic Fit"))
        self.rbtnExp.setText(_translate("Dialog", "Exponential Fit"))
        self.rbtnAll.setText(_translate("Dialog", "All Three"))
        self.groupOutput.setTitle(_translate("Dialog", "Output"))
        self.lblEquation.setText(_translate("Dialog", "Equation:"))
        self.btnCalc.setText(_translate("Dialog", "Calculate"))
        self.btnExit.setText(_translate("Dialog", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
