from PyQt5 import QtCore, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 800)
        self.groupInput = QtWidgets.QGroupBox(Dialog)
        self.groupInput.setGeometry(QtCore.QRect(20, 10, 861, 131))
        self.groupInput.setObjectName("groupInput")
        self.txtFileName = QtWidgets.QLineEdit(self.groupInput)
        self.txtFileName.setGeometry(QtCore.QRect(100, 40, 631, 31))
        self.txtFileName.setReadOnly(False)
        self.txtFileName.setObjectName("txtFileName")
        self.lblFilename = QtWidgets.QLabel(self.groupInput)
        self.lblFilename.setGeometry(QtCore.QRect(30, 40, 61, 31))
        self.lblFilename.setObjectName("lblFilename")
        self.btnSelect = QtWidgets.QPushButton(self.groupInput)
        self.btnSelect.setGeometry(QtCore.QRect(740, 40, 93, 31))
        self.btnSelect.setObjectName("btnSelect")
        self.layoutWidget = QtWidgets.QWidget(self.groupInput)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 80, 801, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbtnLin = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtnLin.setObjectName("rbtnLin")
        self.horizontalLayout.addWidget(self.rbtnLin)
        self.rbtnQuad = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtnQuad.setObjectName("rbtnQuad")
        self.horizontalLayout.addWidget(self.rbtnQuad)
        self.rbtnCubic = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtnCubic.setObjectName("rbtnCubic")
        self.horizontalLayout.addWidget(self.rbtnCubic)
        self.rbtnExp = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtnExp.setChecked(False)
        self.rbtnExp.setObjectName("rbtnExp")
        self.horizontalLayout.addWidget(self.rbtnExp)
        self.rbtnAll = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtnAll.setChecked(True)
        self.rbtnAll.setObjectName("rbtnAll")
        self.horizontalLayout.addWidget(self.rbtnAll)
        self.groupOutput = QtWidgets.QGroupBox(Dialog)
        self.groupOutput.setGeometry(QtCore.QRect(20, 200, 861, 521))
        self.groupOutput.setObjectName("groupOutput")
        self.lblEquation = QtWidgets.QLabel(self.groupOutput)
        self.lblEquation.setGeometry(QtCore.QRect(30, 40, 61, 31))
        self.lblEquation.setObjectName("lblEquation")
        self.txtEquation = QtWidgets.QLineEdit(self.groupOutput)
        self.txtEquation.setGeometry(QtCore.QRect(90, 40, 541, 31))
        self.txtEquation.setReadOnly(True)
        self.txtEquation.setObjectName("txtEquation")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupOutput)
        self.graphicsView.setGeometry(QtCore.QRect(30, 100, 801, 391))
        self.graphicsView.setObjectName("graphicsView")
        self.txtR = QtWidgets.QLineEdit(self.groupOutput)
        self.txtR.setGeometry(QtCore.QRect(690, 40, 141, 31))
        self.txtR.setText("")
        self.txtR.setReadOnly(True)
        self.txtR.setObjectName("txtR")
        self.lblR = QtWidgets.QLabel(self.groupOutput)
        self.lblR.setGeometry(QtCore.QRect(650, 40, 31, 31))
        self.lblR.setObjectName("lblR")
        self.btnCalc = QtWidgets.QPushButton(Dialog)
        self.btnCalc.setGeometry(QtCore.QRect(340, 160, 221, 28))
        self.btnCalc.setObjectName("btnCalc")
        self.btnExit = QtWidgets.QPushButton(Dialog)
        self.btnExit.setGeometry(QtCore.QRect(340, 750, 221, 28))
        self.btnExit.setObjectName("btnExit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupInput.setTitle(_translate("Dialog", "Input"))
        self.lblFilename.setText(_translate("Dialog", "Filename:"))
        self.btnSelect.setText(_translate("Dialog", "Select File"))
        self.rbtnLin.setText(_translate("Dialog", "Linear Fit"))
        self.rbtnQuad.setText(_translate("Dialog", "Quadratic Fit"))
        self.rbtnCubic.setText(_translate("Dialog", "Cubic Fit"))
        self.rbtnExp.setText(_translate("Dialog", "Exponential Fit"))
        self.rbtnAll.setText(_translate("Dialog", "All Four"))
        self.groupOutput.setTitle(_translate("Dialog", "Output"))
        self.lblEquation.setText(_translate("Dialog", "Equation:"))
        self.lblR.setText(_translate("Dialog", "R^2:"))
        self.btnCalc.setText(_translate("Dialog", "Calculate"))
        self.btnExit.setText(_translate("Dialog", "Exit"))

class PlotCanvas(FigureCanvas):
    def __init__(self, parent, width=None, height=None, dpi=100):
        if width == None: width = parent.width()/100
        if height == None: height = parent.height()/100
        fig = Figure(figsize=(width, height), dpi=dpi)
        FigureCanvas.__init__(self, fig)
        self.setParent(parent)

